### ISSUE TITLE
googletest FetchContent_Declare broken

### ISSUE THREAD

**Issue by tarazu** [abs-tudelft/cmake-modules#25]
These lines in `CompileUnits/CompileUnits.cmake`

```
FetchContent_Declare(googletest
  GIT_REPOSITORY  https://github.com/google/googletest.git
  GIT_TAG         master
)
```
is now broken due to tag name being changed in googletest to `main`.

See here:
https://github.com/google/googletest/issues/3663

I got this error when trying to build the fletcher project from source. It worked after I manually changed the tag.

**Comment by mbrobbel** [comment]
Thanks for reporting this!
